# Employee Attrition 

### Import Required Libraries

In [2]:
# Import Required Libraries
import pandas as pd
import sklearn
import sqlite3
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import plotly.io as pio
from statsmodels.formula.api import ols
import statsmodels.api as sm

### Read Employee Attrition Data

In [3]:
df = pd.read_csv('../data/WA_Fn-UseC_-HR-Employee-Attrition.csv')
df.head()

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0   
1  ...                         4            80                 1   
2  ...                         2            80                 0   
3  ...                         3            80                 0   
4  ...                         4            80                 1   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6   
1                 10                      3               3              10   
2                  7                      3               3               0   
3                  8                      3               3               8   
4                  6                      3               3               2   

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                  4                        0                     5  
1                  7                        1                     7  
2                  0                        0                     0  
3                  7                        3                     0  
4                  2                        2                     2  

[5 rows x 35 columns]

# Exploratory Data Analysis

In [47]:
df.shape

(1470, 35)

- The number of employees 1470.
- The number of fetchers 35.

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Age                       1470 non-null   int64 
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64 
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64 
 6   Education                 1470 non-null   int64 
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64 
 9   EmployeeNumber            1470 non-null   int64 
 10  EnvironmentSatisfaction   1470 non-null   int64 
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64 
 13  JobInvolvement            1470 non-null   int64 
 14  JobLevel                

## Chick Numerical Columns

In [49]:
df.describe().T

count          mean          std     min      25%  \
Age                       1470.0     36.923810     9.135373    18.0    30.00   
DailyRate                 1470.0    802.485714   403.509100   102.0   465.00   
DistanceFromHome          1470.0      9.192517     8.106864     1.0     2.00   
Education                 1470.0      2.912925     1.024165     1.0     2.00   
EmployeeCount             1470.0      1.000000     0.000000     1.0     1.00   
EmployeeNumber            1470.0   1024.865306   602.024335     1.0   491.25   
EnvironmentSatisfaction   1470.0      2.721769     1.093082     1.0     2.00   
HourlyRate                1470.0     65.891156    20.329428    30.0    48.00   
JobInvolvement            1470.0      2.729932     0.711561     1.0     2.00   
JobLevel                  1470.0      2.063946     1.106940     1.0     1.00   
JobSatisfaction           1470.0      2.728571     1.102846     1.0     2.00   
MonthlyIncome             1470.0   6502.931293  4707.956783  1009.0  2911.00   
MonthlyRate               1470.0  14313.103401  7117.786044  2094.0  8047.00   
NumCompaniesWorked        1470.0      2.693197     2.498009     0.0     1.00   
PercentSalaryHike         1470.0     15.209524     3.659938    11.0    12.00   
PerformanceRating         1470.0      3.153741     0.360824     3.0     3.00   
RelationshipSatisfaction  1470.0      2.712245     1.081209     1.0     2.00   
StandardHours             1470.0     80.000000     0.000000    80.0    80.00   
StockOptionLevel          1470.0      0.793878     0.852077     0.0     0.00   
TotalWorkingYears         1470.0     11.279592     7.780782     0.0     6.00   
TrainingTimesLastYear     1470.0      2.799320     1.289271     0.0     2.00   
WorkLifeBalance           1470.0      2.761224     0.706476     1.0     2.00   
YearsAtCompany            1470.0      7.008163     6.126525     0.0     3.00   
YearsInCurrentRole        1470.0      4.229252     3.623137     0.0     2.00   
YearsSinceLastPromotion   1470.0      2.187755     3.222430     0.0     0.00   
YearsWithCurrManager      1470.0      4.123129     3.568136     0.0     2.00   

                              50%       75%      max  
Age                          36.0     43.00     60.0  
DailyRate                   802.0   1157.00   1499.0  
DistanceFromHome              7.0     14.00     29.0  
Education                     3.0      4.00      5.0  
EmployeeCount                 1.0      1.00      1.0  
EmployeeNumber             1020.5   1555.75   2068.0  
EnvironmentSatisfaction       3.0      4.00      4.0  
HourlyRate                   66.0     83.75    100.0  
JobInvolvement                3.0      3.00      4.0  
JobLevel                      2.0      3.00      5.0  
JobSatisfaction               3.0      4.00      4.0  
MonthlyIncome              4919.0   8379.00  19999.0  
MonthlyRate               14235.5  20461.50  26999.0  
NumCompaniesWorked            2.0      4.00      9.0  
PercentSalaryHike            14.0     18.00     25.0  
PerformanceRating             3.0      3.00      4.0  
RelationshipSatisfaction      3.0      4.00      4.0  
StandardHours                80.0     80.00     80.0  
StockOptionLevel              1.0      1.00      3.0  
TotalWorkingYears            10.0     15.00     40.0  
TrainingTimesLastYear         3.0      3.00      6.0  
WorkLifeBalance               3.0      3.00      4.0  
YearsAtCompany                5.0      9.00     40.0  
YearsInCurrentRole            3.0      7.00     18.0  
YearsSinceLastPromotion       1.0      3.00     15.0  
YearsWithCurrManager          3.0      7.00     17.0

- No null values 
- `StandardHours` has the same value for all employees.
- `PerformanceRating` has only 2 values 3 or 4.
- The minimum `MonthlyRate` is 2094, with an average 14235, and a maximum of 26999.
- `EmployeeCount`  has 1 for all employees.

### Chick number of uniq values for each column

In [50]:
print("Number of unique values in each numerical column:")
for column in df.select_dtypes(include='int64').columns:
    print(f"{column}: {df[column].nunique()}")

Number of unique values in each numerical column:
Age: 43
DailyRate: 886
DistanceFromHome: 29
Education: 5
EmployeeCount: 1
EmployeeNumber: 1470
EnvironmentSatisfaction: 4
HourlyRate: 71
JobInvolvement: 4
JobLevel: 5
JobSatisfaction: 4
MonthlyIncome: 1349
MonthlyRate: 1427
NumCompaniesWorked: 10
PercentSalaryHike: 15
PerformanceRating: 2
RelationshipSatisfaction: 4
StandardHours: 1
StockOptionLevel: 4
TotalWorkingYears: 40
TrainingTimesLastYear: 7
WorkLifeBalance: 4
YearsAtCompany: 37
YearsInCurrentRole: 19
YearsSinceLastPromotion: 16
YearsWithCurrManager: 18


- `EmployeeNumber` is uniq for each employee. 
- `StandardHours` has the same value for all employees.
- `PerformanceRating` has only 2 values.
- `EmployeeCount`  has the same value for all employees.

## Chick Categorical Columns

In [51]:
df.describe(include='all').T

count unique                     top  freq  \
Age                       1470.0    NaN                     NaN   NaN   
Attrition                   1470      2                      No  1233   
BusinessTravel              1470      3           Travel_Rarely  1043   
DailyRate                 1470.0    NaN                     NaN   NaN   
Department                  1470      3  Research & Development   961   
DistanceFromHome          1470.0    NaN                     NaN   NaN   
Education                 1470.0    NaN                     NaN   NaN   
EducationField              1470      6           Life Sciences   606   
EmployeeCount             1470.0    NaN                     NaN   NaN   
EmployeeNumber            1470.0    NaN                     NaN   NaN   
EnvironmentSatisfaction   1470.0    NaN                     NaN   NaN   
Gender                      1470      2                    Male   882   
HourlyRate                1470.0    NaN                     NaN   NaN   
JobInvolvement            1470.0    NaN                     NaN   NaN   
JobLevel                  1470.0    NaN                     NaN   NaN   
JobRole                     1470      9         Sales Executive   326   
JobSatisfaction           1470.0    NaN                     NaN   NaN   
MaritalStatus               1470      3                 Married   673   
MonthlyIncome             1470.0    NaN                     NaN   NaN   
MonthlyRate               1470.0    NaN                     NaN   NaN   
NumCompaniesWorked        1470.0    NaN                     NaN   NaN   
Over18                      1470      1                       Y  1470   
OverTime                    1470      2                      No  1054   
PercentSalaryHike         1470.0    NaN                     NaN   NaN   
PerformanceRating         1470.0    NaN                     NaN   NaN   
RelationshipSatisfaction  1470.0    NaN                     NaN   NaN   
StandardHours             1470.0    NaN                     NaN   NaN   
StockOptionLevel          1470.0    NaN                     NaN   NaN   
TotalWorkingYears         1470.0    NaN                     NaN   NaN   
TrainingTimesLastYear     1470.0    NaN                     NaN   NaN   
WorkLifeBalance           1470.0    NaN                     NaN   NaN   
YearsAtCompany            1470.0    NaN                     NaN   NaN   
YearsInCurrentRole        1470.0    NaN                     NaN   NaN   
YearsSinceLastPromotion   1470.0    NaN                     NaN   NaN   
YearsWithCurrManager      1470.0    NaN                     NaN   NaN   

                                  mean          std     min     25%      50%  \
Age                           36.92381     9.135373    18.0    30.0     36.0   
Attrition                          NaN          NaN     NaN     NaN      NaN   
BusinessTravel                     NaN          NaN     NaN     NaN      NaN   
DailyRate                   802.485714     403.5091   102.0   465.0    802.0   
Department                         NaN          NaN     NaN     NaN      NaN   
DistanceFromHome              9.192517     8.106864     1.0     2.0      7.0   
Education                     2.912925     1.024165     1.0     2.0      3.0   
EducationField                     NaN          NaN     NaN     NaN      NaN   
EmployeeCount                      1.0          0.0     1.0     1.0      1.0   
EmployeeNumber             1024.865306   602.024335     1.0  491.25   1020.5   
EnvironmentSatisfaction       2.721769     1.093082     1.0     2.0      3.0   
Gender                             NaN          NaN     NaN     NaN      NaN   
HourlyRate                   65.891156    20.329428    30.0    48.0     66.0   
JobInvolvement                2.729932     0.711561     1.0     2.0      3.0   
JobLevel                      2.063946      1.10694     1.0     1.0      2.0   
JobRole                            NaN          NaN     NaN     NaN      NaN   
JobSatisfaction               2.728571

- `Attrition` is the target and has 2 values which make this data suitable for binary classifications tasks and visualizations.
- There are 3 uniq values of `Department` with the highest number of employees in the department of Research & Development department(961).
- `Over18` column only has one value.
- No null values 

### Chick uniq values of Categorical columns

In [52]:
for column in df.select_dtypes(include='object').columns:
    print(f"{column}: {df[column].unique()}")

Attrition: ['Yes' 'No']
BusinessTravel: ['Travel_Rarely' 'Travel_Frequently' 'Non-Travel']
Department: ['Sales' 'Research & Development' 'Human Resources']
EducationField: ['Life Sciences' 'Other' 'Medical' 'Marketing' 'Technical Degree'
 'Human Resources']
Gender: ['Female' 'Male']
JobRole: ['Sales Executive' 'Research Scientist' 'Laboratory Technician'
 'Manufacturing Director' 'Healthcare Representative' 'Manager'
 'Sales Representative' 'Research Director' 'Human Resources']
MaritalStatus: ['Single' 'Married' 'Divorced']
Over18: ['Y']
OverTime: ['Yes' 'No']


## Attributes Description

### Demographic / Personal

<span style="color:green;">Age</span>: Age of the employee.

<span style="color:green;">Gender</span>: Male or Female.

<span style="color:green;">MaritalStatus</span>: Single, Married, Divorced.

<span style="color:green;">Over18</span>: Always "Y" in this dataset <span style="color:crimson; font-weight:bold;">(not useful).</span>


### Job / Work-related

<span style="color:green;">Attrition</span>: Whether the employee left the company (Yes/No).

<span style="color:green;">BusinessTravel</span>: Frequency of travel for work (Non-Travel, Travel_Rarely, Travel_Frequently).

<span style="color:green;">Department</span>: Which department the employee works in (HR, R&D, Sales).

<span style="color:green;">DistanceFromHome</span>: Distance from home to office (in miles).

<span style="color:green;">EmployeeCount</span>: Always 1 <span style="color:crimson; font-weight:bold;">(not useful).</span>

<span style="color:green;">EmployeeNumber</span>: Unique ID for each employee <span style="color:crimson; font-weight:bold;">(not useful).</span>

<span style="color:green;">JobLevel</span>: Level in the company hierarchy (1 = entry-level, 5 = senior executive).

<span style="color:green;">JobRole</span>: Job title (e.g., Sales Executive, Research Scientist).

<span style="color:green;">OverTime</span>: Does the employee work overtime? (Yes/No).

<span style="color:green;">StandardHours</span>: Always 80 <span style="color:crimson; font-weight:bold;">(not useful).</span>

### Compensation

<span style="color:green;">DailyRate</span>: Daily salary rate (arbitrary unit, not directly meaningful).

<span style="color:green;">HourlyRate</span>: Hourly wage rate (arbitrary, like DailyRate).

<span style="color:green;">MonthlyIncome</span>: The actual monthly salary.

<span style="color:green;">MonthlyRate</span>: An HR system field that comes from IBM’s payroll/HR database. It represents an internal payroll rate code <span style="color:crimson; font-weight:bold;">(not rleated).</span>

<span style="color:green;">PercentSalaryHike</span>: % increase in salary last year.

<span style="color:green;">StockOptionLevel</span>:  Employee stock option level (0–3). Higher = more stock options granted as part of compensation.

### Experience / Career
<span style="color:green;">Education</span>: Education level (1 = Below College, …, 5 = Doctorate).

<span style="color:green;">EducationField</span>: Field of study (Life Sciences, Medical, Marketing, etc.).

<span style="color:green;">JobInvolvement</span>: How engaged and dedicated the employee is to their job (1 = Low, …, 4 = Very High).

<span style="color:green;">NumCompaniesWorked</span>: Total number of companies the employee has worked for before joining this one.

<span style="color:green;">TotalWorkingYears</span>: Total years of professional experience.

<span style="color:green;">TrainingTimesLastYear</span>: Number of training programs attended last year.

<span style="color:green;">YearsAtCompany</span>: Years spent at the current company.

<span style="color:green;">YearsInCurrentRole</span>: Years in the current job role.

<span style="color:green;">YearsSinceLastPromotion</span>: Years since the employee was last promoted.

<span style="color:green;">YearsWithCurrManager</span>: Years working with the current manager.


### Satisfaction & Ratings

<span style="color:green;">EnvironmentSatisfaction</span>: How satisfied the employee is with their work environment (1 = Low … 4 = Very High).

<span style="color:green;">JobSatisfaction</span>: How satisfied the employee is with their job overall.

<span style="color:green;">PerformanceRating</span>: Performance appraisal rating (1 = Low, 2 = Good, 3 = Excellent, 4 = Outstanding).

<span style="color:green;">RelationshipSatisfaction</span>: How satisfied an employee is with their interpersonal relationships at work (colleagues, supervisors, etc.).

<span style="color:green;">WorkLifeBalance</span>: Perception of balance between work and personal life (1 = Bad … 4 = Best).

## Data Cleaning

### Duplicated Rows

In [44]:
# Check for duplicate rows
duplicate_rows = df.duplicated()
print(f"Number of duplicate rows: {duplicate_rows.sum()}")

Number of duplicate rows: 0


There are no Duplicated Rows in the data.

### Outlier Analysis

Check for outliers in numerical columns using IQR method and print the number of outliers of each numerical column.

In [ ]:
# Check for outliers in numerical columns using IQR method

# Identify numerical columns
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns

# Initialize a dictionary to hold outlier counts
outlier_summary = {}

# Check for outliers in each numerical column
cols_with_outliers = []
for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    outlier_summary[col] = outliers.shape[0]
    if outliers.shape[0] > 0:
        cols_with_outliers.append(col)

# Print number of outliers of each numerical column
print("Number of outliers in each numerical column:")
for col, count in outlier_summary.items():
    print(f"{col}: {count}")

Number of outliers in each numerical column:
Age: 0
DailyRate: 0
DistanceFromHome: 0
Education: 0
EmployeeCount: 0
EmployeeNumber: 0
EnvironmentSatisfaction: 0
HourlyRate: 0
JobInvolvement: 0
JobLevel: 0
JobSatisfaction: 0
MonthlyIncome: 114
MonthlyRate: 0
NumCompaniesWorked: 52
PercentSalaryHike: 0
PerformanceRating: 226
RelationshipSatisfaction: 0
StandardHours: 0
StockOptionLevel: 85
TotalWorkingYears: 63
TrainingTimesLastYear: 238
WorkLifeBalance: 0
YearsAtCompany: 104
YearsInCurrentRole: 21
YearsSinceLastPromotion: 107
YearsWithCurrManager: 14


Columns with outliers:
- `MonthlyIncome` with 114 outlier.
- `NumCompaniesWorked` with 52 outlier.
- `PerformanceRating` with 226 outlier, and since it only has 2 values either 3 or 4, i am assuming that these 226 instance belong to one of them.
- `StockOptionLevel` with 85 outlier.
- `TotalWorkingYears` with 63 outlier.
- `TrainingTimesLastYear` with 238 outlier.
- `YearsAtCompany` with 104 outlier.
- `YearsInCurrentRole` with 21 outlier.
- `YearsSinceLastPromotion` with 107 outlier.
- `YearsWithCurrManager`  with 107 outlier.

No Need to chick for outlier values in categorical columns since the uniq values of them was checked and they seem normal.

#### Visualize Outliers

Using boxplot to visualize outliers in numerical columns.

In [ ]:
# Visualize outliers using box plots

# Set default renderer to 'notebook_connected' for better compatibility
pio.renderers.default = "notebook_connected"

# Create subplots for box plots
# Adjust number of rows and columns based on number of columns with outliers
n_cols = 4
n_rows = 3

# Create subplots
fig = make_subplots(
    rows=n_rows, 
    cols=n_cols, 
    subplot_titles=cols_with_outliers,
    vertical_spacing=0.05 
)

# Add box plots to subplots
for idx, col in enumerate(cols_with_outliers):
    row = idx // n_cols + 1
    col_pos = idx % n_cols + 1
    fig.add_trace(
        px.box(df, y=col, points='outliers').data[0],
        row=row, col=col_pos
    )

# Update layout
fig.update_layout(
    height=400 * n_rows,
    width=320 * n_cols,
    title_text="Box Plots of Columns with Outliers"
)

# Show the figure
fig.show()

All identified outliers appear reasonable and within acceptable ranges. Since no predictive modeling will be performed, they will not be removed from the dataset.

### Drop Unnecessary Columns

The following columns are dropped as they do not provide useful information for analysis:

- **`EmployeeCount`**: Constant value for all rows.
- **`Over18`**: Constant value for all rows.
- **`MonthlyRate`**: Not directly meaningful for analysis.
- **`StandardHours`**: Constant value for all rows.
- **`EmployeeNumber`**: Serves only as a unique identifier.

In [ ]:
# Drop columns that are not useful for analysis
df = df.drop(['EmployeeCount', 'Over18', 'MonthlyRate', 'StandardHours', 'EmployeeNumber'], axis=1)
df.sample(5)

Age Attrition BusinessTravel  DailyRate              Department  \
999    42        No  Travel_Rarely       1147         Human Resources   
1111   53       Yes  Travel_Rarely        607  Research & Development   
565    23        No  Travel_Rarely        310  Research & Development   
1289   38        No     Non-Travel       1336         Human Resources   
1277   46        No  Travel_Rarely        734  Research & Development   

      DistanceFromHome  Education    EducationField  EnvironmentSatisfaction  \
999                 10          3   Human Resources                        3   
1111                 2          5  Technical Degree                        3   
565                 10          1           Medical                        1   
1289                 2          3   Human Resources                        1   
1277                 2          4           Medical                        3   

      Gender  ...  PerformanceRating  RelationshipSatisfaction  \
999   Female  ...                  3                         3   
1111  Female  ...                  3                         2   
565     Male  ...                  3                         4   
1289    Male  ...                  3                         4   
1277    Male  ...                  3                         3   

      StockOptionLevel TotalWorkingYears  TrainingTimesLastYear  \
999                  1                21                      5   
1111                 1                34                      4   
565                  0                 2                      3   
1289                 3                13                      3   
1277                 1                24                      3   

     WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
999                3              20                   7   
1111               3              33                   7   
565                3               2                   2   
1289               3              11                  10   
1277               3               2                   1   

     YearsSinceLastPromotion  YearsWithCurrManager  
999                        0                     9  
1111                       1                     9  
565                        0                     2  
1289                       3                     8  
1277                       2                     2  

[5 rows x 30 columns]

## Save Cleaned Data

In [ ]:
#df.to_csv('../data/cleanData.csv', index=False)

In [5]:
cleanDf = pd.read_csv('../data/cleanData.csv')
cleanDf.head()

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EnvironmentSatisfaction  \
0                 1          2  Life Sciences                        2   
1                 8          1  Life Sciences                        3   
2                 2          2          Other                        4   
3                 3          4  Life Sciences                        4   
4                 2          1        Medical                        1   

   Gender  ...  PerformanceRating  RelationshipSatisfaction  StockOptionLevel  \
0  Female  ...                  3                         1                 0   
1    Male  ...                  4                         4                 1   
2    Male  ...                  3                         2                 0   
3  Female  ...                  3                         3                 0   
4    Male  ...                  3                         4                 1   

  TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                 8                      0               1               6   
1                10                      3               3              10   
2                 7                      3               3               0   
3                 8                      3               3               8   
4                 6                      3               3               2   

   YearsInCurrentRole YearsSinceLastPromotion  YearsWithCurrManager  
0                   4                       0                     5  
1                   7                       1                     7  
2                   0                       0                     0  
3                   7                       3                     0  
4                   2                       2                     2  

[5 rows x 30 columns]

## Create an SQLite Database

To create an SQL database, the structure of the tables, their relationships, and the attributes, including primary keys (PK) and foreign keys (FK) must be carefully studied. This process involves designing a clear Entity Relationship (ER) model, which can then be transformed into a well structured schema suited to the task


### ER diagram
This ER diagram illustrates a database schema for managing employee information within an organization. It consists of four main entities: Employees, Departments, EducationFields, and Jobs.

#### The ER tables:
1. `Employees` Table: 
This is the central entity, storing detailed information about each employee.

    - `Employee ID` {PK}
    - `Age`
    - `Gender`
    - `MaritalStatus`
    - `DepartmentID` {FK}
    - `JobID` {FK}
    - `EducationFieldID` {FK}
    - `Attrition`
    - `BusinessTravel`
    - `DistanceFromHome`
    - `OverTime`
    - `TrainingTimesLastYear`
    - `NumCompaniesWorked`
    - `TotalWorkingYears`
    - `YearsAtCompany`
    - `YearsInCurrentRole`
    - `YearsSinceLastPromotion`
    - `YearsWithCurrManager`
    - `EnvironmentSatisfaction`
    - `JobSatisfaction`
    - `RelationshipSatisfaction`
    - `WorkLifeBalance`
    - `JobInvolvement`
    - `PerformanceRating`
    - `DailyRate`
    - `HourlyRate`
    - `MonthlyIncome`
    - `PercentSalaryHike`
    - `StockOptionLevel`

2. `Departments` Table: 
This table stores information about the different departments within the organization.

    - `DepartmentID` {PK}
    - `DepartmentName`

3. `EducationFields` Table: 
This table lists various fields of education relevant to the employees.

    - `EducationFieldID` {PK}
    - `FieldName`

4. `Jobs` Table: 
This table defines different job roles and their corresponding levels within the organization.

    - `JobID` {PK}
    - `JobRole`
    - `JobLevel`


#### Relationships
The ER diagram shows three one-to-many relationships, where one record in the parent table can be associated with multiple records in the child table.

1. `Departments` has 1.. `Employees`*: A single department can have one or more employees.
2. `EducationFields` has 1.. `Employees`*: A single education field can be associated with one or more employees.
3. `Jobs` has 1.. `Employees`*: A single job role can be held by one or more employees.

<br><br>

<img src="../db/ERdiagram.png" alt="ER Diagram" width="600"/>

### Create the Schema
The following SQL schema is derived from the ER diagram.  
It defines the tables, their attributes, primary keys (PK), and foreign keys (FK), ensuring proper relationships between employees, departments, jobs, and education fields.

In [ ]:
# Create or connect to the database
conn = sqlite3.connect("../db/employee_database.db")
cur = conn.cursor()

# Drop tables if they already exist (for re-run safety)
tables = ["Employees", "Departments", "Jobs", "EducationFields"]
for t in tables:
    cur.execute(f"DROP TABLE IF EXISTS {t}")

# 1. Departments table
cur.execute("""
CREATE TABLE Departments (
    DepartmentID INTEGER PRIMARY KEY AUTOINCREMENT,
    DepartmentName TEXT UNIQUE
);
""")

# 2. Jobs table
cur.execute("""
CREATE TABLE Jobs (
    JobID INTEGER PRIMARY KEY AUTOINCREMENT,
    JobRole TEXT,
    JobLevel INTEGER
);
""")

# 3. EducationFields table
cur.execute("""
CREATE TABLE EducationFields (
    EducationFieldID INTEGER PRIMARY KEY AUTOINCREMENT,
    FieldName TEXT UNIQUE
);
""")

# 4. Employees table 
cur.execute("""
CREATE TABLE Employees (
    EmployeeID INTEGER PRIMARY KEY AUTOINCREMENT,
    Age INTEGER,
    Gender TEXT,
    MaritalStatus TEXT,
    DepartmentID INTEGER,
    JobID INTEGER,
    EducationFieldID INTEGER,

    -- Attrition & Travel
    Attrition TEXT,
    BusinessTravel TEXT,
    DistanceFromHome INTEGER,
    OverTime TEXT,
    TrainingTimesLastYear INTEGER,

    -- WorkHistory
    NumCompaniesWorked INTEGER,
    TotalWorkingYears INTEGER,
    YearsAtCompany INTEGER,
    YearsInCurrentRole INTEGER,
    YearsSinceLastPromotion INTEGER,
    YearsWithCurrManager INTEGER,

    -- Satisfaction
    EnvironmentSatisfaction INTEGER,
    JobSatisfaction INTEGER,
    RelationshipSatisfaction INTEGER,
    WorkLifeBalance INTEGER,
    JobInvolvement INTEGER,
    PerformanceRating INTEGER,

    -- Compensation
    DailyRate INTEGER,
    HourlyRate INTEGER,
    MonthlyIncome INTEGER,
    PercentSalaryHike INTEGER,
    StockOptionLevel INTEGER,

    FOREIGN KEY (DepartmentID) REFERENCES Departments(DepartmentID),
    FOREIGN KEY (JobID) REFERENCES Jobs(JobID),
    FOREIGN KEY (EducationFieldID) REFERENCES EducationFields(EducationFieldID)
);
""")

# Commit changes and close
conn.commit()
conn.close()

### Fill Database With Employee Data

The database will be filled with employee data from the cleaned Pandas Dataframe.

In [ ]:
# Connect to SQLite DB
conn = sqlite3.connect("../db/employee_database.db")
cur = conn.cursor()

# Insert unique Departments 
departments = cleanDf["Department"].dropna().unique()
for dept in departments:
    cur.execute("INSERT OR IGNORE INTO Departments (DepartmentName) VALUES (?)", (dept,))

# Insert unique Jobs 
jobs = cleanDf[["JobRole", "JobLevel"]].drop_duplicates()
for _, row in jobs.iterrows():
    cur.execute("INSERT OR IGNORE INTO Jobs (JobRole, JobLevel) VALUES (?, ?)", 
                (row["JobRole"], int(row["JobLevel"])))

# Insert unique EducationFields 
edu_fields = cleanDf["EducationField"].dropna().unique()
for field in edu_fields:
    cur.execute("INSERT OR IGNORE INTO EducationFields (FieldName) VALUES (?)", (field,))

conn.commit()

# Create mapping dictionaries for lookups 
cur.execute("SELECT DepartmentID, DepartmentName FROM Departments")
dept_map = {name: id for id, name in cur.fetchall()}

cur.execute("SELECT JobID, JobRole, JobLevel FROM Jobs")
job_map = {(role, level): id for id, role, level in cur.fetchall()}

cur.execute("SELECT EducationFieldID, FieldName FROM EducationFields")
edu_map = {name: id for id, name in cur.fetchall()}

# Insert Employees 
for _, row in cleanDf.iterrows():
    cur.execute("""
        INSERT INTO Employees (
            Age, Gender, MaritalStatus, DepartmentID, JobID, EducationFieldID,
            Attrition, BusinessTravel, DistanceFromHome, OverTime, TrainingTimesLastYear,
            NumCompaniesWorked, TotalWorkingYears, YearsAtCompany, YearsInCurrentRole,
            YearsSinceLastPromotion, YearsWithCurrManager,
            EnvironmentSatisfaction, JobSatisfaction, RelationshipSatisfaction,
            WorkLifeBalance, JobInvolvement, PerformanceRating,
            DailyRate, HourlyRate, MonthlyIncome, PercentSalaryHike, StockOptionLevel
        ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
    """, (
        int(row["Age"]) if not pd.isna(row["Age"]) else None,
        row["Gender"],
        row["MaritalStatus"],
        dept_map.get(row["Department"]),
        job_map.get((row["JobRole"], int(row["JobLevel"]))),
        edu_map.get(row["EducationField"]),
        row["Attrition"],
        row["BusinessTravel"],
        int(row["DistanceFromHome"]) if not pd.isna(row["DistanceFromHome"]) else None,
        row["OverTime"],
        int(row["TrainingTimesLastYear"]) if not pd.isna(row["TrainingTimesLastYear"]) else None,
        int(row["NumCompaniesWorked"]) if not pd.isna(row["NumCompaniesWorked"]) else None,
        int(row["TotalWorkingYears"]) if not pd.isna(row["TotalWorkingYears"]) else None,
        int(row["YearsAtCompany"]) if not pd.isna(row["YearsAtCompany"]) else None,
        int(row["YearsInCurrentRole"]) if not pd.isna(row["YearsInCurrentRole"]) else None,
        int(row["YearsSinceLastPromotion"]) if not pd.isna(row["YearsSinceLastPromotion"]) else None,
        int(row["YearsWithCurrManager"]) if not pd.isna(row["YearsWithCurrManager"]) else None,
        int(row["EnvironmentSatisfaction"]) if not pd.isna(row["EnvironmentSatisfaction"]) else None,
        int(row["JobSatisfaction"]) if not pd.isna(row["JobSatisfaction"]) else None,
        int(row["RelationshipSatisfaction"]) if not pd.isna(row["RelationshipSatisfaction"]) else None,
        int(row["WorkLifeBalance"]) if not pd.isna(row["WorkLifeBalance"]) else None,
        int(row["JobInvolvement"]) if not pd.isna(row["JobInvolvement"]) else None,
        int(row["PerformanceRating"]) if not pd.isna(row["PerformanceRating"]) else None,
        int(row["DailyRate"]) if not pd.isna(row["DailyRate"]) else None,
        int(row["HourlyRate"]) if not pd.isna(row["HourlyRate"]) else None,
        int(row["MonthlyIncome"]) if not pd.isna(row["MonthlyIncome"]) else None,
        int(row["PercentSalaryHike"]) if not pd.isna(row["PercentSalaryHike"]) else None,
        int(row["StockOptionLevel"]) if not pd.isna(row["StockOptionLevel"]) else None
    ))

conn.commit()
conn.close()

### Show the Database

This code makes sure that the data was filled correctly by  printing the tables and sample data from them.

In [ ]:
# List all tables in the SQLite database
conn = sqlite3.connect('../db/employee_database.db')
tables_df = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", conn)
print("Tables in the database:")
print(tables_df)

# Show the first 5 rows of each table
for table_name in tables_df['name']:
    print(f"\nFirst 5 rows of table '{table_name}':")
    display(pd.read_sql_query(f"SELECT * FROM {table_name} LIMIT 5;", conn))

conn.close()

Tables in the database:
              name
0  sqlite_sequence
1      Departments
2             Jobs
3  EducationFields
4        Employees

First 5 rows of table 'sqlite_sequence':


name   seq
0      Departments     6
1             Jobs    52
2  EducationFields    12
3        Employees  1470


First 5 rows of table 'Departments':


DepartmentID          DepartmentName
0             1                   Sales
1             2  Research & Development
2             3         Human Resources


First 5 rows of table 'Jobs':


JobID                 JobRole  JobLevel
0      1         Sales Executive         2
1      2      Research Scientist         2
2      3   Laboratory Technician         1
3      4      Research Scientist         1
4      5  Manufacturing Director         3


First 5 rows of table 'EducationFields':


EducationFieldID         FieldName
0                 1     Life Sciences
1                 2             Other
2                 3           Medical
3                 4         Marketing
4                 5  Technical Degree


First 5 rows of table 'Employees':


EmployeeID  Age  Gender MaritalStatus  DepartmentID  JobID  \
0           1   41  Female        Single             1     27   
1           2   49    Male       Married             2     28   
2           3   37    Male        Single             2     29   
3           4   33  Female       Married             2     30   
4           5   27    Male       Married             2     29   

   EducationFieldID Attrition     BusinessTravel  DistanceFromHome  ...  \
0                 1       Yes      Travel_Rarely                 1  ...   
1                 1        No  Travel_Frequently                 8  ...   
2                 2       Yes      Travel_Rarely                 2  ...   
3                 1        No  Travel_Frequently                 3  ...   
4                 3        No      Travel_Rarely                 2  ...   

  JobSatisfaction  RelationshipSatisfaction  WorkLifeBalance  JobInvolvement  \
0               4                         1                1               3   
1               2                         4                3               2   
2               3                         2                3               2   
3               3                         3                3               3   
4               2                         4                3               3   

   PerformanceRating  DailyRate  HourlyRate  MonthlyIncome  PercentSalaryHike  \
0                  3       1102          94           5993                 11   
1                  4        279          61           5130                 23   
2                  3       1373          92           2090                 15   
3                  3       1392          56           2909                 11   
4                  3        591          40           3468                 12   

   StockOptionLevel  
0                 0  
1                 1  
2                 0  
3                 0  
4                 1  

[5 rows x 29 columns]

## Answering Key Questions

This section will address important questions about the employee dataset. each question below will be answered in two ways:  
1. Using ``pandas`` for a DataFrame  
2. Using ``SQLite`` queries for a database 

Then the answers will be visualized.

### Q1- How many total employees are there?

In [ ]:
# --------------------------- 
# Using pandas
# --------------------------- 
total_employees_pandas = cleanDf.shape[0]
print(f"Total employees (pandas): {total_employees_pandas}")

# --------------------------- 
# Using SQLite
# --------------------------- 

# connect to the database
conn = sqlite3.connect("../db/employee_database.db")
cur = conn.cursor()

# Execute the query
cur.execute("SELECT COUNT(*) FROM Employees")
total_employees_sqlite = cur.fetchone()[0]

# Print the result and close the connection
print(f"Total employees (SQLite): {total_employees_sqlite}")
conn.close()

Total employees (pandas): 1470
Total employees (SQLite): 1470


### Answer Q1 
The total number of employees in the data is 1470.

### Q2- What is the employee count for each department?

In [ ]:
# ---------------------------
# Using pandas
# ---------------------------
dept_counts_pandas = cleanDf['Department'].value_counts()
print("Employee count for each department (pandas):")
print(dept_counts_pandas)

# ---------------------------
# Using SQLite
# ---------------------------

# Connect to the database
conn = sqlite3.connect("../db/employee_database.db")
cur = conn.cursor()

# Execute the query
cur.execute("""
    SELECT d.DepartmentName, COUNT(e.EmployeeID) as EmployeeCount
    FROM Employees e
    JOIN Departments d ON e.DepartmentID = d.DepartmentID
    GROUP BY d.DepartmentName
""")

# Fetch and print results
dept_counts_sqlite = cur.fetchall()
print("\nEmployee count for each department (SQLite):")
for dept, count in dept_counts_sqlite:
    print(f"{dept}: {count}")

# Close the connection
conn.close()

Employee count for each department (pandas):
Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

Employee count for each department (SQLite):
Human Resources: 63
Research & Development: 961
Sales: 446


### Answer Q2

Employee count for each department:

1. `Research & Development`:    961
2. `Sales`:                     446
3. `Human Resources`:            63

#### Visualize Answer Q1 & Q2

The pie chart below shows the count and distribution of employees across different departments.  
Each slice represents a department, annotated with the number of employees and their percentage of the total workforce.  
The total number of employees is included in the chart title for reference.

In [ ]:
# Calculate total employees
total_employees = len(cleanDf)

# Create pie chart with counts
fig = px.pie(cleanDf, 
             names='Department',
             title=f'Employee Distribution by Department (Total Employees: {total_employees})',
             hole=0.3,  # optional donut style
             labels={'Department': 'Department', 'value': 'Number of Employees'})

# Show counts on slices
fig.update_traces(textinfo='label+value+percent')  # show department name, count, and percentage

# Display the plot
fig.show()

### Q3- What is the average monthly income by job role?

In [ ]:
# ---------------------------
# Using pandas
# ---------------------------

avg_income_by_jobrole_pandas = cleanDf.groupby('JobRole')['MonthlyIncome'].mean().sort_values(ascending=False)
print("Average monthly income by job role (pandas):")
print(avg_income_by_jobrole_pandas)

# ---------------------------
# Using SQLite
# ---------------------------

# Connect to the database
conn = sqlite3.connect("../db/employee_database.db")
cur = conn.cursor()

# Execute the query
cur.execute("""
    SELECT j.JobRole, AVG(e.MonthlyIncome) as AvgMonthlyIncome
    FROM Employees e
    JOIN Jobs j ON e.JobID = j.JobID
    GROUP BY j.JobRole
    ORDER BY AvgMonthlyIncome DESC
""")

# Fetch and print results
avg_income_by_jobrole_sqlite = cur.fetchall()
print("\nAverage monthly income by job role (SQLite):")
for jobrole, avg_income in avg_income_by_jobrole_sqlite:
    print(f"{jobrole}: {avg_income:.2f}")
conn.close()

Average monthly income by job role (pandas):
JobRole
Manager                      17181.676471
Research Director            16033.550000
Healthcare Representative     7528.763359
Manufacturing Director        7295.137931
Sales Executive               6924.279141
Human Resources               4235.750000
Research Scientist            3239.972603
Laboratory Technician         3237.169884
Sales Representative          2626.000000
Name: MonthlyIncome, dtype: float64

Average monthly income by job role (SQLite):
Manager: 17181.68
Research Director: 16033.55
Healthcare Representative: 7528.76
Manufacturing Director: 7295.14
Sales Executive: 6924.28
Human Resources: 4235.75
Research Scientist: 3239.97
Laboratory Technician: 3237.17
Sales Representative: 2626.00


### Answer Q3

THe Average monthly income by job role:

- `Manager`:                       17181
- `Research Director`:           16033
- `Healthcare Representative`:     7528
- `Manufacturing Director`:        7295
- `Sales Executive`:               6924
- `Human Resources`:               4235
- `Research Scientist`:            3239
- `Laboratory Technician`:        3237
- `Sales Representative`:          2626

#### Visualize Answer Q3
The bar chart below shows the average monthly income for each job role in the data.  
The bars are sorted from highest to lowest average income, with the values.  

In [ ]:
# Calculate average monthly income by JobRole
avg_income_by_jobrole = cleanDf.groupby('JobRole')['MonthlyIncome'].mean().sort_values(ascending=False).reset_index()

# Create bar chart
fig = px.bar(avg_income_by_jobrole, 
             x='JobRole', 
             y='MonthlyIncome',
             title='Average Monthly Income by Job Role',
             labels={'JobRole': 'Job Role', 'MonthlyIncome': 'Average Monthly Income'},
             text='MonthlyIncome')  

# Format numbers with commas
fig.update_traces(texttemplate='%{text:,.0f}', textposition='outside')

# Improve layout
fig.update_layout(xaxis_tickangle=-45, yaxis_tickformat=',.0f')

# Show plot
fig.show()

### Q4- Who are the top 5 employees by performance rating for each department?

<span style="color:yellow;">⚠ Note on Data Bias:</span>

The `PerformanceRating` column is not a reliable indicator of employee performance in this dataset. It only contains two unique values:

- `3 (Excellent)` → 1244 employees

- `4 (Outstanding)` → 226 employees

There are no employees with ratings `1 (Low)` or `2 (Good)`, which means the data is heavily skewed toward higher ratings. 


In addition, HR employees (or managers) might feel uncomfortable assigning low ratings to their colleagues even when they are deserved, which can further contribute to inflated ratings and bias.

As a result, any analysis or conclusions drawn from `PerformanceRating` may therefore be biased and not representative of true performance differences.


Since there are 226 employees with a `PerformanceRating` of 4 across all departments, the data has been sorted in descending order of `monthlyIncome` to highlight the highest earning employee with a performance rating of 4 in each department.

In [ ]:
# ---------------------------
# Using pandas
# ---------------------------

# Get top 5 employees by performance rating for each department in a descending order of monthly income
top5_by_dept_pandas = (
    cleanDf.sort_values(['Department', 'PerformanceRating', 'MonthlyIncome'], ascending=[True, False, False])
    .groupby('Department')
    .head(5)
    .loc[:, ['Department', 'Age', 'Gender', 'JobRole', 'JobLevel', 'PerformanceRating', 'MonthlyIncome']]
)
print("Top 5 employees by performance rating for each department (pandas):")

# Display results for each department
for dept in top5_by_dept_pandas['Department'].unique():
    print(f"\nDepartment: {dept}")
    display(
        top5_by_dept_pandas[top5_by_dept_pandas['Department'] == dept]
        .drop(columns='Department')
        .reset_index(drop=True)
    )

# ---------------------------
# Using SQLite
# ---------------------------

# Connect to the database
conn = sqlite3.connect("../db/employee_database.db")

# Execute the query for top 5 employees by performance rating for each department in a descending order of monthly income
query = """
SELECT *
FROM (
    SELECT 
        e.Age,
        e.Gender,
        j.JobRole,
        j.JobLevel,
        e.PerformanceRating,
        e.MonthlyIncome,
        ROW_NUMBER() OVER (
            PARTITION BY d.DepartmentName
            ORDER BY e.PerformanceRating DESC, e.MonthlyIncome DESC
        ) as rn,
        d.DepartmentName
    FROM Employees e
    JOIN Departments d ON e.DepartmentID = d.DepartmentID
    JOIN Jobs j ON e.JobID = j.JobID
)
WHERE rn <= 5
ORDER BY DepartmentName, rn
"""
top5_by_dept_sqlite = pd.read_sql_query(query, conn)
print("Top 5 employees by performance rating for each department (SQLite):")

# Display results for each department
for dept in top5_by_dept_sqlite['DepartmentName'].unique():
    print(f"\nDepartment: {dept}")
    display(
        top5_by_dept_sqlite[top5_by_dept_sqlite['DepartmentName'] == dept]
        .drop(columns=['rn', 'DepartmentName'])
        .reset_index(drop=True)
    )
conn.close()

Top 5 employees by performance rating for each department (pandas):

Department: Human Resources


Age  Gender          JobRole  JobLevel  PerformanceRating  MonthlyIncome
0   59  Female          Manager         5                  4          18844
1   40    Male          Manager         4                  4          16437
2   45  Female  Human Resources         3                  4           9756
3   46    Male  Human Resources         2                  4           5021
4   36    Male  Human Resources         2                  4           3886


Department: Research & Development


Age  Gender            JobRole  JobLevel  PerformanceRating  MonthlyIncome
0   41  Female  Research Director         5                  4          19973
1   58  Female  Research Director         5                  4          19701
2   42    Male            Manager         5                  4          19613
3   45  Female            Manager         5                  4          18061
4   50  Female            Manager         4                  4          17856


Department: Sales


Age  Gender  JobRole  JobLevel  PerformanceRating  MonthlyIncome
0   51    Male  Manager         5                  4          19847
1   55    Male  Manager         5                  4          19586
2   46  Female  Manager         4                  4          17048
3   55  Female  Manager         4                  4          16835
4   58    Male  Manager         4                  4          16291

Top 5 employees by performance rating for each department (SQLite):

Department: Human Resources


Age  Gender          JobRole  JobLevel  PerformanceRating  MonthlyIncome
0   59  Female          Manager         5                  4          18844
1   40    Male          Manager         4                  4          16437
2   45  Female  Human Resources         3                  4           9756
3   46    Male  Human Resources         2                  4           5021
4   36    Male  Human Resources         2                  4           3886


Department: Research & Development


Age  Gender            JobRole  JobLevel  PerformanceRating  MonthlyIncome
0   41  Female  Research Director         5                  4          19973
1   58  Female  Research Director         5                  4          19701
2   42    Male            Manager         5                  4          19613
3   45  Female            Manager         5                  4          18061
4   50  Female            Manager         4                  4          17856


Department: Sales


Age  Gender  JobRole  JobLevel  PerformanceRating  MonthlyIncome
0   51    Male  Manager         5                  4          19847
1   55    Male  Manager         5                  4          19586
2   46  Female  Manager         4                  4          17048
3   55  Female  Manager         4                  4          16835
4   58    Male  Manager         4                  4          16291

### Answer Q4
<h3>Top 5 highest earning employees with a performance rating of 4 in each department.</h3>

<h4>Department: Human Resources</h4>
<table border="1" cellpadding="5" cellspacing="0">
  <tr>
    <th>Age</th>
    <th>Gender</th>
    <th>JobRole</th>
    <th>JobLevel</th>
    <th>PerformanceRating</th>
    <th>MonthlyIncome</th>
  </tr>
  <tr><td>59</td><td>Female</td><td>Manager</td><td>5</td><td>4</td><td>18844</td></tr>
  <tr><td>40</td><td>Male</td><td>Manager</td><td>4</td><td>4</td><td>16437</td></tr>
  <tr><td>45</td><td>Female</td><td>Human Resources</td><td>3</td><td>4</td><td>9756</td></tr>
  <tr><td>46</td><td>Male</td><td>Human Resources</td><td>2</td><td>4</td><td>5021</td></tr>
  <tr><td>36</td><td>Male</td><td>Human Resources</td><td>2</td><td>4</td><td>3886</td></tr>
</table>

<h4>Department: Research & Development</h4>
<table border="1" cellpadding="5" cellspacing="0">
  <tr>
    <th>Age</th>
    <th>Gender</th>
    <th>JobRole</th>
    <th>JobLevel</th>
    <th>PerformanceRating</th>
    <th>MonthlyIncome</th>
  </tr>
  <tr><td>41</td><td>Female</td><td>Research Director</td><td>5</td><td>4</td><td>19973</td></tr>
  <tr><td>58</td><td>Female</td><td>Research Director</td><td>5</td><td>4</td><td>19701</td></tr>
  <tr><td>42</td><td>Male</td><td>Manager</td><td>5</td><td>4</td><td>19613</td></tr>
  <tr><td>45</td><td>Female</td><td>Manager</td><td>5</td><td>4</td><td>18061</td></tr>
  <tr><td>50</td><td>Female</td><td>Manager</td><td>4</td><td>4</td><td>17856</td></tr>
</table>

<h4>Department: Sales</h4>
<table border="1" cellpadding="5" cellspacing="0">
  <tr>
    <th>Age</th>
    <th>Gender</th>
    <th>JobRole</th>
    <th>JobLevel</th>
    <th>PerformanceRating</th>
    <th>MonthlyIncome</th>
  </tr>
  <tr><td>51</td><td>Male</td><td>Manager</td><td>5</td><td>4</td><td>19847</td></tr>
  <tr><td>55</td><td>Male</td><td>Manager</td><td>5</td><td>4</td><td>19586</td></tr>
  <tr><td>46</td><td>Female</td><td>Manager</td><td>4</td><td>4</td><td>17048</td></tr>
  <tr><td>55</td><td>Female</td><td>Manager</td><td>4</td><td>4</td><td>16835</td></tr>
  <tr><td>58</td><td>Male</td><td>Manager</td><td>4</td><td>4</td><td>16291</td></tr>
</table>

#### Visualize Answer Q4
The scatter plot below shows the monthly incomes of all employees with a Performance Rating of 4, grouped by department.  
Each point represents an individual employee
This visualization helps compare the distribution of high-performing employees' salaries across different departments.

In [ ]:
# Filter employees with PerformanceRating = 4
performance_4_df = cleanDf[cleanDf['PerformanceRating'] == 4]

# Create a scatter/strip plot
fig = px.strip(
    performance_4_df,
    x='Department',
    y='MonthlyIncome',
    color='Department',
    hover_data=['JobRole', 'Age', 'JobLevel'],  # info on hover
    title='Monthly Income of Employees with Performance Rating = 4 by Department'
)

# Add jitter for better separation of points
fig.update_traces(jitter=0.3, marker=dict(size=8, line=dict(width=1, color='DarkSlateGrey')))

fig.update_layout(
    xaxis_title='Department',
    yaxis_title='Monthly Income',
    showlegend=False
)

fig.show()

### Q5- Which department has the highest average performance rating?

In [ ]:
# ---------------------------
# Using pandas
# ---------------------------

# Get average performance rating by department
avg_perf_by_dept_pandas = cleanDf.groupby('Department')['PerformanceRating'].mean().sort_values(ascending=False)
top_dept_pandas = avg_perf_by_dept_pandas.idxmax()
print(f"Department with highest average performance rating (pandas): {top_dept_pandas} with rating {avg_perf_by_dept_pandas.max():.2f}")

# ---------------------------
# Using SQLite
# ---------------------------

# Connect to the database
conn = sqlite3.connect("../db/employee_database.db")
cur = conn.cursor()

# Execute the query
cur.execute("""
    SELECT d.DepartmentName, AVG(e.PerformanceRating) as AvgPerformanceRating
    FROM Employees e
    JOIN Departments d ON e.DepartmentID = d.DepartmentID
    GROUP BY d.DepartmentName
    ORDER BY AvgPerformanceRating DESC
    LIMIT 1
""")

# Fetch and print result
top_dept_sqlite = cur.fetchone()
print(f"Department with highest average performance rating (SQLite): {top_dept_sqlite[0]} with rating {top_dept_sqlite[1]:.2f}")
conn.close()

Department with highest average performance rating (pandas): Research & Development with rating 3.16
Department with highest average performance rating (SQLite): Research & Development with rating 3.16


### Answer Q5

The Department with highest average `performanceRating` : `Research & Development` with a rating of 3.16

#### Visualize Answer Q5
The bar chart below shows the average performance rating for each department.  
The height of each bar represents the mean performance rating of employees within that department.

In [ ]:
# Calculate average performance rating by department
avg_perf_by_dept = cleanDf.groupby('Department')['PerformanceRating'].mean().sort_values(ascending=False).reset_index()

# Create bar chart
fig = px.bar(
    avg_perf_by_dept,
    x='Department',
    y='PerformanceRating',
    text='PerformanceRating',
    title='Average Performance Rating by Department',
    labels={'PerformanceRating': 'Average Performance Rating', 'Department': 'Department'},
    color='PerformanceRating',  # color by rating
    color_continuous_scale='Blues'
)

# Show values on top of bars
fig.update_traces(texttemplate='%{text:.2f}', textposition='outside')
fig.update_layout(yaxis_range=[0,5], xaxis_tickangle=-45, showlegend=False, height=500)

fig.show()

## Additional Attrition Related Questions

### Q6- Which combinations of department and job role have the highest attrition rates?

In [ ]:
# ---------------------------
# Using pandas
# ---------------------------

# Group by Department and JobRole to calculate attrition rates
attrition_by_dept_job_pandas = (
    cleanDf.groupby(['Department', 'JobRole'])
    .agg(
        TotalEmployees=('Attrition', 'count'),
        AttritionCount=('Attrition', lambda x: (x == 'Yes').sum())
    )
    .reset_index()
)

# Calculate attrition rate
attrition_by_dept_job_pandas['AttritionRate'] = (
    attrition_by_dept_job_pandas['AttritionCount'] / attrition_by_dept_job_pandas['TotalEmployees']
).round(2)

# Sort by AttritionRate desc, then TotalEmployees desc
attrition_by_dept_job_pandas = attrition_by_dept_job_pandas.sort_values(
    ['AttritionRate', 'TotalEmployees'], ascending=[False, False]
).reset_index(drop=True)

# Display top 10 combinations with highest attrition rates
print("Department & JobRole combinations with highest attrition rates (pandas):")
display(attrition_by_dept_job_pandas.head(10))


# ---------------------------
# Using SQLite
# ---------------------------

# Connect to the database
conn = sqlite3.connect("../db/employee_database.db")

# Execute the query
query = """
SELECT 
    d.DepartmentName,
    j.JobRole,
    COUNT(e.EmployeeID) AS TotalEmployees,
    SUM(CASE WHEN e.Attrition = 'Yes' THEN 1 ELSE 0 END) AS AttritionCount,
    ROUND(1.0 * SUM(CASE WHEN e.Attrition = 'Yes' THEN 1 ELSE 0 END) / COUNT(e.EmployeeID), 2) AS AttritionRate
FROM Employees e
JOIN Departments d ON e.DepartmentID = d.DepartmentID
JOIN Jobs j ON e.JobID = j.JobID
GROUP BY d.DepartmentName, j.JobRole
ORDER BY AttritionRate DESC, TotalEmployees DESC
LIMIT 10
"""
attrition_by_dept_job_sqlite = pd.read_sql_query(query, conn)
conn.close()

# Display results
print("Department & JobRole combinations with highest attrition rates (SQLite):")
display(attrition_by_dept_job_sqlite)

Department & JobRole combinations with highest attrition rates (pandas):


Department                    JobRole  TotalEmployees  \
0                   Sales       Sales Representative              83   
1  Research & Development      Laboratory Technician             259   
2         Human Resources            Human Resources              52   
3                   Sales            Sales Executive             326   
4  Research & Development         Research Scientist             292   
5  Research & Development     Manufacturing Director             145   
6  Research & Development  Healthcare Representative             131   
7  Research & Development                    Manager              54   
8                   Sales                    Manager              37   
9  Research & Development          Research Director              80   

   AttritionCount  AttritionRate  
0              33           0.40  
1              62           0.24  
2              12           0.23  
3              57           0.17  
4              47           0.16  
5              10           0.07  
6               9           0.07  
7               3           0.06  
8               2           0.05  
9               2           0.02

Department & JobRole combinations with highest attrition rates (SQLite):


DepartmentName                    JobRole  TotalEmployees  \
0                   Sales       Sales Representative              83   
1  Research & Development      Laboratory Technician             259   
2         Human Resources            Human Resources              52   
3                   Sales            Sales Executive             326   
4  Research & Development         Research Scientist             292   
5  Research & Development     Manufacturing Director             145   
6  Research & Development  Healthcare Representative             131   
7  Research & Development                    Manager              54   
8                   Sales                    Manager              37   
9  Research & Development          Research Director              80   

   AttritionCount  AttritionRate  
0              33           0.40  
1              62           0.24  
2              12           0.23  
3              57           0.17  
4              47           0.16  
5              10           0.07  
6               9           0.07  
7               3           0.06  
8               2           0.05  
9               2           0.03

### Answer Q6
The Department & JobRole combinations with highest attrition rates:
1. `Sales` department and `Sales Representative` Rule with an attrition of 40 %.
2. `Research & Development` department and `Laboratory Technician` role with an attrition of 24 %.
3. `Human Resources` department and `Human Resources` role with an attrition of 23 %.
4. `Sales department` and `Sales Executive` role with an attrition of 17 %.
5. `Research & Development` department and `Research Scientist` role with an attrition of 16 %.

#### Visualize Answer Q6
The horizontal bar chart below shows the **top 10 Department and Job Role combinations with the highest attrition rates**.  
Each bar represents a combination of department and job role, with the length indicating the attrition rate.  
The bars are color-coded by attrition rate, and exact values are displayed on top for clarity.

In [29]:
# Take the top 10 combinations with highest attrition rates
top10_attrition = attrition_by_dept_job_pandas.head(10).copy()

# Combine Department and JobRole for better labeling
top10_attrition['Dept_Job'] = top10_attrition['Department'] + ' - ' + top10_attrition['JobRole']

# Create horizontal bar chart
fig = px.bar(
    top10_attrition.sort_values('AttritionRate', ascending=True),  # ascending for horizontal bars
    x='AttritionRate',
    y='Dept_Job',
    orientation='h',
    text='AttritionRate',
    title='Top 10 Department & JobRole Combinations by Attrition Rate',
    labels={'AttritionRate': 'Attrition Rate', 'Dept_Job': 'Department - Job Role'},
    color='AttritionRate',
    color_continuous_scale='Reds'
)

# Show values on bars
fig.update_traces(texttemplate='%{text:.2f}', textposition='outside')

# Layout adjustments
fig.update_layout(yaxis={'categoryorder':'total ascending'}, height=500, showlegend=False)

fig.show()

### Q7- What is the average tenure (YearsAtCompany) for employees who left the company compared to those who stayed?

In [ ]:
# ---------------------------
# Using pandas
# ---------------------------

# Calculate average tenure by attrition status
avg_tenure_pandas = (
    cleanDf.groupby('Attrition')
    .agg(AverageTenure=('YearsAtCompany', 'mean'))
    .round(2)
    .reset_index()
)

# Display results
print("Average tenure by attrition status (pandas):")
display(avg_tenure_pandas)


# ---------------------------
# Using SQLite
# ---------------------------

# Connect to the database
conn = sqlite3.connect("../db/employee_database.db")

# Execute the query
query = """
SELECT 
    Attrition,
    ROUND(AVG(YearsAtCompany), 2) AS AverageTenure
FROM Employees
GROUP BY Attrition
"""

# Fetch and display results
avg_tenure_sqlite = pd.read_sql_query(query, conn)
conn.close()

# Display results
print("Average tenure by attrition status (SQLite):")
display(avg_tenure_sqlite)

Average tenure by attrition status (pandas):


Attrition  AverageTenure
0        No           7.37
1       Yes           5.13

Average tenure by attrition status (SQLite):


Attrition  AverageTenure
0        No           7.37
1       Yes           5.13

### Answer Q7

The average tenure of employees differs depending on whether they left the company or stayed:

- Employees who stayed `(Attrition = No)` have an average tenure of 7.37 years.

- Employees who left `(Attrition = Yes)` have a lower average tenure of 5.13 years.

This indicates that employees who leave the company tend to have shorter tenure compared to those who remain.

#### Visualize Answer Q7

The bar chart below compares the **average tenure (Years at Company)** of employees who left the company versus those who stayed.  
This visualization highlights that employees who left generally had a **shorter tenure** compared to employees who remained, providing insights into workforce retention trends.


In [32]:
# Create bar chart
fig = px.bar(
    avg_tenure_pandas,
    x='Attrition',
    y='AverageTenure',
    text='AverageTenure',
    color='Attrition',
    title='Average Tenure by Attrition Status',
    labels={'AverageTenure': 'Average Tenure (Years)', 'Attrition': 'Attrition Status'},
    color_discrete_map={'Yes':'#EF553B','No':'#636EFA'}  # optional: red for Yes, blue for No
)

# Show values on top of bars
fig.update_traces(texttemplate='%{text:.2f}', textposition='outside')

# Layout adjustments
fig.update_layout(yaxis_range=[0, avg_tenure_pandas['AverageTenure'].max() + 1], showlegend=False)

fig.show()

### Q8- Does working overtime correlate with a higher attrition rate?

In [ ]:
# ---------------------------
# Using pandas
# ---------------------------

# Group by OverTime and calculate attrition rate
overtime_attrition_pandas = (
    cleanDf.groupby('OverTime')
    .agg(
        TotalEmployees=('Attrition', 'count'),
        AttritionCount=('Attrition', lambda x: (x == 'Yes').sum())
    )
    .reset_index()
)

# Calculate attrition rate
overtime_attrition_pandas['AttritionRate'] = (
    overtime_attrition_pandas['AttritionCount'] / overtime_attrition_pandas['TotalEmployees']
).round(2)

# Display results
print("Attrition rate by Overtime status (pandas):")
display(overtime_attrition_pandas)


# ---------------------------
# Using SQLite
# ---------------------------

# Connect to the database
conn = sqlite3.connect("../db/employee_database.db")

# Execute the query
query = """
SELECT 
    OverTime,
    COUNT(EmployeeID) AS TotalEmployees,
    SUM(CASE WHEN Attrition = 'Yes' THEN 1 ELSE 0 END) AS AttritionCount,
    ROUND(1.0 * SUM(CASE WHEN Attrition = 'Yes' THEN 1 ELSE 0 END) / COUNT(EmployeeID), 2) AS AttritionRate
FROM Employees
GROUP BY OverTime
"""
overtime_attrition_sqlite = pd.read_sql_query(query, conn)
conn.close()

# Display results
print("Attrition rate by Overtime status (SQLite):")
display(overtime_attrition_sqlite)

Attrition rate by Overtime status (pandas):


OverTime  TotalEmployees  AttritionCount  AttritionRate
0       No            1054             110           0.10
1      Yes             416             127           0.31

Attrition rate by Overtime status (SQLite):


OverTime  TotalEmployees  AttritionCount  AttritionRate
0       No            1054             110           0.10
1      Yes             416             127           0.31

### Answer Q8

Yes, working overtime correlates with a higher attrition rate.

- Employees who do not work overtime have an attrition rate of 10% (110 out of 1,054 employees).

- Employees who do work overtime have an attrition rate of 31% (127 out of 416 employees).

This shows that employees who work overtime are over three times more likely to leave the company compared to those who don’t.

#### Visualize Answer Q8

The bar chart below shows the **attrition rate based on overtime status**.  
It compares employees who work overtime (`Yes`) with those who do not (`No`).  
This visualization highlights the strong correlation between working overtime and higher attrition rates.

In [34]:
# Create bar chart
fig = px.bar(
    overtime_attrition_pandas,
    x='OverTime',
    y='AttritionRate',
    text='AttritionRate',
    color='OverTime',
    title='Attrition Rate by OverTime Status',
    labels={'AttritionRate': 'Attrition Rate', 'OverTime': 'OverTime Status'},
    color_discrete_map={'Yes':'#EF553B','No':'#636EFA'}  # red for employees with overtime
)

# Show values on top of bars
fig.update_traces(texttemplate='%{text:.2f}', textposition='outside')

# Layout adjustments
fig.update_layout(yaxis_range=[0,1], showlegend=False, height=500)

fig.show()

### Q9- Are employees with low performance ratings more likely to leave? Compare attrition rates by PerformanceRating.

In [ ]:
# ---------------------------
# Using pandas
# ---------------------------

# Group by PerformanceRating and calculate attrition rate
performance_attrition_pandas = (
    cleanDf.groupby('PerformanceRating')
    .agg(
        TotalEmployees=('Attrition', 'count'),
        AttritionCount=('Attrition', lambda x: (x == 'Yes').sum())
    )
    .reset_index()
)

# Calculate attrition rate
performance_attrition_pandas['AttritionRate'] = (
    performance_attrition_pandas['AttritionCount'] / performance_attrition_pandas['TotalEmployees']
).round(2)
# Sort values
performance_attrition_pandas = performance_attrition_pandas.sort_values('PerformanceRating')

# Display results
print("Attrition rate by PerformanceRating (pandas):")
display(performance_attrition_pandas)


# ---------------------------
# Using SQLite
# ---------------------------

# Connect to the database
conn = sqlite3.connect("../db/employee_database.db")

# Execute the query
query = """
SELECT 
    PerformanceRating,
    COUNT(EmployeeID) AS TotalEmployees,
    SUM(CASE WHEN Attrition = 'Yes' THEN 1 ELSE 0 END) AS AttritionCount,
    ROUND(1.0 * SUM(CASE WHEN Attrition = 'Yes' THEN 1 ELSE 0 END) / COUNT(EmployeeID), 2) AS AttritionRate
FROM Employees
GROUP BY PerformanceRating
ORDER BY PerformanceRating
"""
performance_attrition_sqlite = pd.read_sql_query(query, conn)
conn.close()

# Display results
print("Attrition rate by PerformanceRating (SQLite):")
display(performance_attrition_sqlite)

Attrition rate by PerformanceRating (pandas):


PerformanceRating  TotalEmployees  AttritionCount  AttritionRate
0                  3            1244             200           0.16
1                  4             226              37           0.16

Attrition rate by PerformanceRating (SQLite):


PerformanceRating  TotalEmployees  AttritionCount  AttritionRate
0                  3            1244             200           0.16
1                  4             226              37           0.16

The table shows that employees with a performance rating of **3 (Excellent)** and those with a rating of **4 (Outstanding)** both have an attrition rate of **16%**. This indicates that there is **no meaningful difference in attrition based on performance rating** within this dataset.  

This finding supports our earlier note on **data bias**:

- The `PerformanceRating` column only contains two values (`3` and `4`), with no employees rated `1 (Low)` or `2 (Good)`.  
- The distribution is heavily skewed toward higher ratings, which reduces the ability of this variable to distinguish between different levels of performance.  
- In practice, HR staff or managers may also feel uncomfortable assigning low ratings to employees even when warranted, contributing to **rating inflation**.  

As a result, the `PerformanceRating` variable is **not a reliable indicator of true employee performance** and provides little value in explaining attrition.

### Answer Q9

No, employees with low performance ratings are not more likely to leave based on this dataset.

- Employees rated 3 (Excellent) have an attrition rate of 16%.

- Employees rated 4 (Outstanding) also have an attrition rate of 16%.

This shows no meaningful difference in attrition rates between the two performance levels.


However, this result should be interpreted with caution due to data limitations:

- The `PerformanceRating` column only includes ratings of 3 and 4, with no employees rated 1 (Low) or 2 (Good).

- The distribution is skewed toward higher ratings, limiting its usefulness in distinguishing performance differences.

- This may reflect rating inflation, where managers avoid giving low ratings, reducing the reliability of this metric.

Therefore, **PerformanceRating** is not a strong predictor of attrition in this dataset.

#### Visualize Answer Q9

The bar chart below displays the **attrition rate by performance rating**.  
It compares employees with a rating of **3 (Excellent)** and **4 (Outstanding)**, showing the proportion of employees who left in each group.

In [36]:
# Create bar chart
fig = px.bar(
    performance_attrition_pandas,
    x='PerformanceRating',
    y='AttritionRate',
    text='AttritionRate',
    color='AttritionRate',
    color_continuous_scale='Reds',
    title='Attrition Rate by Performance Rating',
    labels={'PerformanceRating': 'Performance Rating', 'AttritionRate': 'Attrition Rate'}
)

# Show values on top of bars
fig.update_traces(texttemplate='%{text:.2f}', textposition='outside')

# Layout adjustments
fig.update_layout(yaxis_range=[0,1], xaxis=dict(dtick=1), showlegend=False, height=500)

fig.show()

### Q9- Are employees with low Job Satisfaction ratings more likely to leave? Compare attrition rates by PerformanceRating.

**Here We can replace `PerformanceRating` with `JobSatisfaction`**

In [ ]:
# ---------------------------
# Using pandas
# ---------------------------

# Group by JobSatisfaction and calculate attrition rate
satisfaction_attrition_pandas = (
    cleanDf.groupby('JobSatisfaction')
    .agg(
        TotalEmployees=('Attrition', 'count'),
        AttritionCount=('Attrition', lambda x: (x == 'Yes').sum())
    )
    .reset_index()
)

# Calculate attrition rate
satisfaction_attrition_pandas['AttritionRate'] = (
    satisfaction_attrition_pandas['AttritionCount'] / satisfaction_attrition_pandas['TotalEmployees']
).round(2)
# Sort values
satisfaction_attrition_pandas = satisfaction_attrition_pandas.sort_values('JobSatisfaction')

print("Attrition rate by JobSatisfaction (pandas):")
display(satisfaction_attrition_pandas)


# ---------------------------
# Using SQLite
# ---------------------------

# Connect to the database
conn = sqlite3.connect("../db/employee_database.db")

# Execute the query
query = """
SELECT 
    JobSatisfaction,
    COUNT(EmployeeID) AS TotalEmployees,
    SUM(CASE WHEN Attrition = 'Yes' THEN 1 ELSE 0 END) AS AttritionCount,
    ROUND(1.0 * SUM(CASE WHEN Attrition = 'Yes' THEN 1 ELSE 0 END) / COUNT(EmployeeID), 2) AS AttritionRate
FROM Employees
GROUP BY JobSatisfaction
ORDER BY JobSatisfaction
"""
satisfaction_attrition_sqlite = pd.read_sql_query(query, conn)
conn.close()
# Display results
print("Attrition rate by JobSatisfaction (SQLite):")
display(satisfaction_attrition_sqlite)

Attrition rate by JobSatisfaction (pandas):


JobSatisfaction  TotalEmployees  AttritionCount  AttritionRate
0                1             289              66           0.23
1                2             280              46           0.16
2                3             442              73           0.17
3                4             459              52           0.11

Attrition rate by JobSatisfaction (SQLite):


JobSatisfaction  TotalEmployees  AttritionCount  AttritionRate
0                1             289              66           0.23
1                2             280              46           0.16
2                3             442              73           0.17
3                4             459              52           0.11

### Answer Q9

Yes, employees with lower Job Satisfaction ratings are more likely to leave.

From the data:

- Employees with Job Satisfaction = 1 (Low) have the highest attrition rate at 23%.

- Employees with Job Satisfaction = 2 show an attrition rate of 16%.

- Employees with Job Satisfaction = 3 have a similar attrition rate of 17%.

- Employees with Job Satisfaction = 4 (Very High) have the lowest attrition rate at 11%.

This indicates a clear negative relationship between job satisfaction and attrition:
as job satisfaction increases, the likelihood of leaving decreases.

**Compared to Performance Rating, where no difference was observed, Job Satisfaction is a stronger predictor of attrition in this dataset.**

#### Visualize Answer Q9

The bar chart below shows the **attrition rate across different levels of Job Satisfaction**.  
It highlights how employees with lower satisfaction levels tend to leave at higher rates, while those with higher satisfaction show lower attrition.  
This visualization provides insight into the relationship between job satisfaction and employee retention.


In [38]:
# Create bar chart
fig = px.bar(
    satisfaction_attrition_pandas,
    x='JobSatisfaction',
    y='AttritionRate',
    text='AttritionRate',
    color='AttritionRate',
    color_continuous_scale='Oranges',
    title='Attrition Rate by Job Satisfaction',
    labels={'JobSatisfaction': 'Job Satisfaction', 'AttritionRate': 'Attrition Rate'}
)

# Show values on top of bars
fig.update_traces(texttemplate='%{text:.2f}', textposition='outside')

# Layout adjustments
fig.update_layout(yaxis_range=[0,1], xaxis=dict(dtick=1), showlegend=False, height=500)

fig.show()

### Q10- Analyze the impact of WorkLifeBalance on attrition. Which balance level has the highest attrition percentage?

In [ ]:
# ---------------------------
# Using pandas
# ---------------------------

# Group by WorkLifeBalance and calculate attrition rate
wlb_attrition_pandas = (
    cleanDf.groupby('WorkLifeBalance')
    .agg(
        TotalEmployees=('Attrition', 'count'),
        AttritionCount=('Attrition', lambda x: (x == 'Yes').sum())
    )
    .reset_index()
)
# Calculate attrition rate
wlb_attrition_pandas['AttritionRate'] = (
    wlb_attrition_pandas['AttritionCount'] / wlb_attrition_pandas['TotalEmployees']
).round(2)
# Sort values
wlb_attrition_pandas = wlb_attrition_pandas.sort_values('WorkLifeBalance')
# Display results
print("Attrition rate by WorkLifeBalance (pandas):")
display(wlb_attrition_pandas)


# ---------------------------
# Using SQLite
# ---------------------------

# Connect to the database
conn = sqlite3.connect("../db/employee_database.db")

# Execute the query
query = """
SELECT 
    WorkLifeBalance,
    COUNT(EmployeeID) AS TotalEmployees,
    SUM(CASE WHEN Attrition = 'Yes' THEN 1 ELSE 0 END) AS AttritionCount,
    ROUND(1.0 * SUM(CASE WHEN Attrition = 'Yes' THEN 1 ELSE 0 END) / COUNT(EmployeeID), 2) AS AttritionRate
FROM Employees
GROUP BY WorkLifeBalance
ORDER BY WorkLifeBalance
"""
wlb_attrition_sqlite = pd.read_sql_query(query, conn)
conn.close()

# Display results
print("Attrition rate by WorkLifeBalance (SQLite):")
display(wlb_attrition_sqlite)

Attrition rate by WorkLifeBalance (pandas):


WorkLifeBalance  TotalEmployees  AttritionCount  AttritionRate
0                1              80              25           0.31
1                2             344              58           0.17
2                3             893             127           0.14
3                4             153              27           0.18

Attrition rate by WorkLifeBalance (SQLite):


WorkLifeBalance  TotalEmployees  AttritionCount  AttritionRate
0                1              80              25           0.31
1                2             344              58           0.17
2                3             893             127           0.14
3                4             153              27           0.18

### Answer Q10

Work-Life Balance has a noticeable impact on attrition rates.

- Employees with **WorkLifeBalance = 1 (Poor)** have the highest attrition rate at 31%.

- Employees with **WorkLifeBalance = 2 (Fair)** show an attrition rate of 17%.

- Employees with **WorkLifeBalance = 3 (Good)** have the lowest attrition rate at 14%.

- Employees with **WorkLifeBalance = 4 (Excellent)** show a slightly higher attrition rate of 18% compared to “Good.”

This indicates that employees with poor work-life balance are more than twice as likely to leave compared to those with a “good” balance.

While attrition is lowest at **WorkLifeBalance = 3 (Good)**, the worst retention problem is clearly at **level 1 (Poor)**, where nearly one-third of employees leave.

#### Visualize Answer Q10
The bar chart below shows the **attrition rate by different levels of Work-Life Balance**.  
It illustrates how employees with a **poor work-life balance** face the highest attrition risk, while those with better balance generally have lower attrition rates.

In [40]:
# Create bar chart
fig = px.bar(
    wlb_attrition_pandas,
    x='WorkLifeBalance',
    y='AttritionRate',
    text='AttritionRate',
    color='AttritionRate',
    color_continuous_scale='Viridis',
    title='Attrition Rate by Work-Life Balance',
    labels={'WorkLifeBalance': 'Work-Life Balance', 'AttritionRate': 'Attrition Rate'}
)

# Show values on top of bars
fig.update_traces(texttemplate='%{text:.2f}', textposition='outside')

# Layout adjustments
fig.update_layout(yaxis_range=[0,1], xaxis=dict(dtick=1), showlegend=False, height=500)

fig.show()

### Q11- Does longer distance from home increase attrition?

In [ ]:
# ---------------------------
# Using pandas
# ---------------------------

# Group by Attrition and calculate average DistanceFromHome
distance_attrition_pandas = (
    cleanDf.groupby('Attrition')
    .agg(
        EmployeeCount=('Attrition', 'count'),
        AverageDistance=('DistanceFromHome', 'mean')
    )
    .round(2)
    .reset_index()
)

# Display results
print("Employee counts and average DistanceFromHome by Attrition status (pandas):")
display(distance_attrition_pandas)

# ---------------------------
# Using SQLite
# ---------------------------

# Connect to the database
conn = sqlite3.connect("../db/employee_database.db")

# Execute the query
query = """
SELECT 
    Attrition,
    COUNT(EmployeeID) AS EmployeeCount,
    ROUND(AVG(DistanceFromHome), 2) AS AverageDistance
FROM Employees
GROUP BY Attrition
"""
distance_attrition_sqlite = pd.read_sql_query(query, conn)
conn.close()

# Display results
print("Average DistanceFromHome by Attrition status (SQLite):")
display(distance_attrition_sqlite)

Employee counts and average DistanceFromHome by Attrition status (pandas):


Attrition  EmployeeCount  AverageDistance
0        No           1233             8.92
1       Yes            237            10.63

Average DistanceFromHome by Attrition status (SQLite):


Attrition  EmployeeCount  AverageDistance
0        No           1233             8.92
1       Yes            237            10.63

### Answer Q11

Yes, employees who live farther from their workplace are slightly more likely to leave.

- Employees who stayed with the company (`Attrition = No`) have an average distance from home of 8.92 km.

- Employees who left the company (`Attrition = Yes`) live farther away on average, at 10.63 km.

This suggests that a longer commute may contribute to higher attrition, though the difference (about 1.7 km) is relatively modest.

Distance from home could be one of several factors influencing attrition, especially when combined with other workplace stressors such as overtime or poor work-life balance.

#### Visualize Answer Q11

The bar chart below compares the **average distance from home** for employees who stayed versus those who left the company.  
It shows that employees who live farther away tend to have a **slightly higher attrition rate**, suggesting that longer commutes may contribute to employee turnover.

In [42]:
# Create bar chart
fig = px.bar(
    distance_attrition_pandas,
    x='Attrition',
    y='AverageDistance',
    text='AverageDistance',
    color='Attrition',
    title='Average Distance From Home by Attrition Status',
    labels={'AverageDistance': 'Average Distance (km)', 'Attrition': 'Attrition Status'},
    color_discrete_map={'Yes':'#EF553B','No':'#636EFA'}  # red for Yes, blue for No
)

# Show values on top of bars
fig.update_traces(texttemplate='%{text:.2f}', textposition='outside')

# Layout adjustments
fig.update_layout(yaxis_range=[0, distance_attrition_pandas['AverageDistance'].max() + 5], showlegend=False, height=500)

fig.show()

### Q12- Do employees with lower recent salary hikes leave the company more often?

In [ ]:
# ---------------------------
# Using pandas
# ---------------------------

# Group by Attrition and calculate average PercentSalaryHike
salaryhike_attrition_pandas = (
    cleanDf.groupby('Attrition')
    .agg(
        EmployeeCount=('Attrition', 'count'),
        AverageSalaryHike=('PercentSalaryHike', 'mean')
    )
    .round(2)
    .reset_index()
)

# Display results
print("Average PercentSalaryHike by Attrition status (pandas):")
display(salaryhike_attrition_pandas)


# ---------------------------
# Using SQLite
# ---------------------------

# Connect to the database
conn = sqlite3.connect("../db/employee_database.db")

# Execute the query
query = """
SELECT
    Attrition,
    COUNT(EmployeeID) AS EmployeeCount,
    ROUND(AVG(PercentSalaryHike), 2) AS AverageSalaryHike
FROM Employees
GROUP BY Attrition
ORDER BY Attrition
"""
salaryhike_attrition_sqlite = pd.read_sql_query(query, conn)
conn.close()

# Display results
print("Average PercentSalaryHike by Attrition status (SQLite):")
display(salaryhike_attrition_sqlite)

Average PercentSalaryHike by Attrition status (pandas):


Attrition  EmployeeCount  AverageSalaryHike
0        No           1233              15.23
1       Yes            237              15.10

Average PercentSalaryHike by Attrition status (SQLite):


Attrition  EmployeeCount  AverageSalaryHike
0        No           1233              15.23
1       Yes            237              15.10

### Answer Q12

No, employees with lower recent salary hikes do not appear to leave more often based on this dataset.

- Employees who stayed (`Attrition = No`) received an average salary hike of **15.23%**.

- Employees who left (`Attrition = Yes`) received an average salary hike of **15.10%**.

The difference is very small (0.13%), indicating that recent salary increases have little impact on attrition in this dataset.

Other factors, such as work-life balance, overtime, or job satisfaction, likely play a more significant role in employee turnover.

#### Visualize Answer Q12

The bar chart below shows the **average percent salary hike** for employees who stayed versus those who left the company.  
It highlights that there is **little difference in recent salary increases** between the two groups, suggesting that salary hikes have a minimal impact on employee attrition in this dataset.

In [44]:
# Create bar chart
fig = px.bar(
    salaryhike_attrition_pandas,
    x='Attrition',
    y='AverageSalaryHike',
    text='AverageSalaryHike',
    color='Attrition',
    title='Average Percent Salary Hike by Attrition Status',
    labels={'AverageSalaryHike': 'Average Percent Salary Hike', 'Attrition': 'Attrition Status'},
    color_discrete_map={'Yes':'#EF553B','No':'#636EFA'}  # red for Yes, blue for No
)

# Show values on top of bars
fig.update_traces(texttemplate='%{text:.2f}', textposition='outside')

# Layout adjustments
fig.update_layout(yaxis_range=[0, salaryhike_attrition_pandas['AverageSalaryHike'].max() + 5], showlegend=False, height=500)

fig.show()


# Visualizations 

In [43]:
numerical_cols = cleanDf.select_dtypes(include=["number"]).columns

discrete_cols = [col for col in numerical_cols if cleanDf[col].nunique() <= 25]
continuous_cols = [col for col in numerical_cols if cleanDf[col].nunique() > 25]

In [ ]:
cols_per_row = 3
num_cols = len(continuous_cols)
num_rows = (num_cols + cols_per_row - 1) // cols_per_row 

fig_cont = make_subplots(
    rows=num_rows,
    cols=cols_per_row,
    subplot_titles=continuous_cols,
    horizontal_spacing=0.1, 
    vertical_spacing=0.15   
)

for i, col in enumerate(continuous_cols):
    row = i // cols_per_row + 1
    col_position = i % cols_per_row + 1
    fig_cont.add_trace(
        go.Histogram(x=cleanDf[col], nbinsx=42, name=str(col)),
        row=row,
        col=col_position
    )

fig_cont.update_layout(
    height=300*num_rows,
    width=1200,
    showlegend=False,
    title_text="Continuous Feature Distributions"
)

fig_cont.show()

In [ ]:
cols_per_row = 3
num_cols = len(discrete_cols)
num_rows = (num_cols + cols_per_row - 1) // cols_per_row 

fig_disc = make_subplots(
    rows=num_rows,
    cols=cols_per_row,
    subplot_titles=discrete_cols,
    horizontal_spacing=0.1,  
    vertical_spacing=0.05 
)

for i, col in enumerate(discrete_cols):
    row = i // cols_per_row + 1
    col_position = i % cols_per_row + 1
    counts = cleanDf[col].value_counts().sort_index()
    fig_disc.add_trace(
        go.Bar(x=counts.index, y=counts.values, name=str(col)),
        row=row,
        col=col_position
    )

fig_disc.update_layout(
    height=300*num_rows,  
    width=1200,
    showlegend=False,
    title_text="Discrete Numerical Feature Counts"
)

fig_disc.show()

In [ ]:
categorical_cols = cleanDf.select_dtypes(exclude=["number"]).columns
cols_per_row = 3
num_cols = len(categorical_cols)
num_rows = (num_cols + cols_per_row - 1) // cols_per_row 

fig_cat = make_subplots(
    rows=num_rows,
    cols=cols_per_row,
    subplot_titles=categorical_cols,
    horizontal_spacing=0.1, 
    vertical_spacing=0.15    
)

for i, col in enumerate(categorical_cols):
    row = i // cols_per_row + 1
    col_position = i % cols_per_row + 1
    counts = cleanDf[col].value_counts()
    fig_cat.add_trace(
        go.Bar(x=counts.index, y=counts.values, name=str(col)),
        row=row,
        col=col_position
    )

fig_cat.update_layout(
    height=300*num_rows,  
    width=1200,
    showlegend=False,
    title_text="Categorical Feature Distributions"
)

fig_cat.show()

In [ ]:
df_corr = cleanDf.copy()
df_corr['AttritionFlag'] = df_corr['Attrition'].map({'Yes': 1, 'No': 0})

numeric_cols = df_corr.select_dtypes(include=['int64', 'float64']).columns.tolist()

corr_matrix = df_corr[numeric_cols].corr()

attrition_corr = corr_matrix['AttritionFlag'].drop('AttritionFlag').reset_index()
attrition_corr.columns = ['Feature', 'CorrelationWithAttrition']

fig = px.bar(
    attrition_corr.sort_values('CorrelationWithAttrition', key=abs, ascending=False),
    x='Feature',
    y='CorrelationWithAttrition',
    title="Correlation of Numerical Features with Attrition",
    labels={'CorrelationWithAttrition': 'Correlation (Attrition=1 Yes, 0 No)'},
    color='CorrelationWithAttrition',
    color_continuous_scale='RdBu',
)
fig.show()


In [ ]:
df_corr = cleanDf.copy()
df_corr['AttritionFlag'] = df_corr['Attrition'].map({'Yes': 1, 'No': 0})

corr_matrix = df_corr[numeric_cols].corr().round(2)


fig = px.imshow(
    corr_matrix,
    text_auto=True, 
    aspect="auto",
    color_continuous_scale="RdBu_r",
    title="Correlation Heatmap of Numerical Features (Including AttritionFlag)"
)

fig.update_layout(
    xaxis_title="Features",
    yaxis_title="Features",
    width=900,
    height=800
)

fig.show()


In [ ]:
df = cleanDf.copy()
df['Attrition_num'] = df['Attrition'].map({'No': 0, 'Yes': 1})

categorical_cols = [
    'BusinessTravel', 'Department', 'EducationField', 
    'Gender', 'JobRole', 'MaritalStatus', 'OverTime'
]

anova_results = {}

for col in categorical_cols:
    model = ols(f'Attrition_num ~ C({col})', data=df).fit()
    anova_table = sm.stats.anova_lm(model, typ=2)
    p_value = anova_table["PR(>F)"][0]
    anova_results[col] = p_value

# Sort by p-value
anova_results = dict(sorted(anova_results.items(), key=lambda item: item[1]))
for feature, pval in anova_results.items():
    print(f"{feature}: p-value = {pval:.5f}")

OverTime: p-value = 0.00000
JobRole: p-value = 0.00000
MaritalStatus: p-value = 0.00000
BusinessTravel: p-value = 0.00001
Department: p-value = 0.00449
EducationField: p-value = 0.00667
Gender: p-value = 0.25909


C:\Users\warif\AppData\Local\Temp\ipykernel_23964\2414221641.py:19: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\warif\AppData\Local\Temp\ipykernel_23964\2414221641.py:19: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\warif\AppData\Local\Temp\ipykernel_23964\2414221641.py:19: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\warif\AppData\Local\Temp\ipykernel_23964\2414221641.py:19: FutureWarning:

Series.__g

In [ ]:
# encode binary attrition
df = cleanDf.copy()
df['Attrition_num'] = df['Attrition'].map({'No': 0, 'Yes': 1})

categorical_cols = [
    'BusinessTravel', 'Department', 'EducationField', 
    'Gender', 'JobRole', 'MaritalStatus', 'OverTime'
]

# calculate ANOVA p-values
anova_results = {}
for col in categorical_cols:
    model = ols(f'Attrition_num ~ C({col})', data=df).fit()
    anova_table = sm.stats.anova_lm(model, typ=2)
    p_value = anova_table["PR(>F)"][0]
    anova_results[col] = p_value

# subplots
cols_per_row = 3
num_cols = len(categorical_cols)
num_rows = (num_cols + cols_per_row - 1) // cols_per_row  

fig = make_subplots(
    rows=num_rows,
    cols=cols_per_row,
    subplot_titles=[f"{col} (p={anova_results[col]:.3g})" for col in categorical_cols],
    horizontal_spacing=0.1,
    vertical_spacing=0.15
)

for i, col in enumerate(categorical_cols):
    row = i // cols_per_row + 1
    col_position = i % cols_per_row + 1
    
    mean_df = df.groupby(col)['Attrition_num'].mean().reset_index(name='AttritionRate')
    
    fig.add_trace(
        go.Bar(
            x=mean_df[col],
            y=mean_df['AttritionRate'],
            text=[f"{v:.2f}" for v in mean_df['AttritionRate']],
            textposition='outside',
            name=col
        ),
        row=row,
        col=col_position
    )

fig.update_layout(
    height=300*num_rows,
    width=1200,
    showlegend=False,
    title_text="Categorical Features vs Attrition Rate with ANOVA p-values"
)

fig.show()

C:\Users\warif\AppData\Local\Temp\ipykernel_23964\568840460.py:21: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\warif\AppData\Local\Temp\ipykernel_23964\568840460.py:21: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\warif\AppData\Local\Temp\ipykernel_23964\568840460.py:21: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\warif\AppData\Local\Temp\ipykernel_23964\568840460.py:21: FutureWarning:

Series.__getit

In [ ]:
attention_col = "Attrition"
numerical_cols = cleanDf.select_dtypes(include=["number"]).columns

# sepearate discrete and continuous numerical
discrete_cols = [col for col in numerical_cols if cleanDf[col].nunique() <= 10]
continuous_cols = [col for col in numerical_cols if cleanDf[col].nunique() > 10]

# violin subplots
def create_violin_subplots(cols, df, title):
    cols_per_row = 2
    num_cols = len(cols)
    num_rows = (num_cols + cols_per_row - 1) // cols_per_row

    fig = make_subplots(
        rows=num_rows,
        cols=cols_per_row,
        subplot_titles=cols,
        vertical_spacing=0.05,
        horizontal_spacing=0.1
    )

    for i, col in enumerate(cols):
        row = i // cols_per_row + 1
        col_position = i % cols_per_row + 1

        fig.add_trace(
            go.Violin(
                y=df[col],
                x=df[attention_col],
                box_visible=True,
                points=False,           
                meanline_visible=True,
                name=col
            ),
            row=row,
            col=col_position
        )

    fig.update_layout(
        height=300*num_rows,
        width=1200,
        showlegend=False,
        title_text=title
    )
    fig.show()

# continuous numerical columns
create_violin_subplots(continuous_cols, cleanDf, "Continuous Numerical Features by Attrition")

In [78]:
# Discrete numerical columns
create_violin_subplots(discrete_cols, cleanDf, "Discrete Numerical Features by Attrition")

# Insights 

## Insight 1
The features that most strongly influence employee attrition are:

1. JobRole
    - Certain roles, such as Sales Representative, show higher attrition rates.
    - Attrition rate for Sales Representative: 0.40
    - ANOVA p-value: 0.000

2. OverTime
    - Employees working overtime (Yes) are more likely to leave.
    - Attrition rate for Yes: 0.31
    - ANOVA p-value: 0.000

3. MaritalStatus
    - Single employees tend to leave more often than married or divorced employees.
    - Attrition rate for Single: 0.26
    - ANOVA p-value: 0.000

4. BusinessTravel
    - Travel_Frequently employees leave more often than Non-Travel or Travel_Rarely.
    - Attrition rate for Travel_Frequently: 0.25
    - ANOVA p-value: 0.000


## Insight 2

The following features are likely to influence employee attrition, though their effects are slightly weaker than the top features:

1. Education Field
    - Employees studying Human Resources are more likely to leave.
    - Attrition rate for Human Resources: 0.26
    - ANOVA p-value: 0.0067

2. Job Level
    - Lower job levels are associated with higher attrition.
    - Correlation with Attrition: -0.17 (slightly negative)
    - Violin plots indicate higher attrition among employees in lower job levels.

3. Monthly Income
    - Employees with lower monthly income tend to leave more frequently.
    - Correlation with Attrition: -0.16 (slightly negative)
    - Violin plots visually support this trend.

4. Tenure-related features
    - Total Working Years, Age, Years with Current Manager, and Years in Current Role
    - Lower values in these features are associated with higher attrition.
    - Slightly negative for all tenure-related features, ranging from -0.16, with Total Working Years showing the strongest negative correlation at -0.17.
    - Violin plots show higher attrition rates for employees with lower tenure and experience.

## Insight 3
The following features slightly influence employee attrition:

1. Job Satisfaction & Environment Satisfaction
    - Employees with lower job satisfaction or lower environment satisfaction tend to have higher attrition rates.
    - Violin plots clearly show that attrition is concentrated among employees with lower satisfaction scores.

2. Daily Rate & Hourly Rate
    - Employees with lower daily or hourly rates are slightly more likely to leave.
    - Violin plots indicate higher attrition among employees with lower pay rates.

## Insight 4

The following features appear to have little or no influence on employee attrition:

1. Salary Hike
2. Stock Option Level
3. Training Times Last Year
4. Relationship Satisfaction

Analysis and visualizations indicate that variations in these features do not significantly affect attrition rates.